# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'olfactometer.ui'
#
# Created: Mon Apr 15 13:47:01 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(894, 808)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.getInfoTab = QtGui.QWidget()
        self.getInfoTab.setObjectName(_fromUtf8("getInfoTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.getInfoTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.getInfoPushButton = QtGui.QPushButton(self.getInfoTab)
        self.getInfoPushButton.setObjectName(_fromUtf8("getInfoPushButton"))
        self.verticalLayout_2.addWidget(self.getInfoPushButton)
        self.line_11 = QtGui.QFrame(self.getInfoTab)
        self.line_11.setMinimumSize(QtCore.QSize(0, 20))
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.verticalLayout_2.addWidget(self.line_11)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.deviceCountLabel = QtGui.QLabel(self.getInfoTab)
        self.deviceCountLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.deviceCountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.deviceCountLabel.setObjectName(_fromUtf8("deviceCountLabel"))
        self.horizontalLayout_3.addWidget(self.deviceCountLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.line_12 = QtGui.QFrame(self.getInfoTab)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.verticalLayout_2.addWidget(self.line_12)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.deviceLabel_0 = QtGui.QLabel(self.getInfoTab)
        self.deviceLabel_0.setMaximumSize(QtCore.QSize(16777215, 20))
        self.deviceLabel_0.setAlignment(QtCore.Qt.AlignCenter)
        self.deviceLabel_0.setObjectName(_fromUtf8("deviceLabel_0"))
        self.horizontalLayout_2.addWidget(self.deviceLabel_0)
        self.deviceLabel_1 = QtGui.QLabel(self.getInfoTab)
        self.deviceLabel_1.setMaximumSize(QtCore.QSize(16777215, 20))
        self.deviceLabel_1.setAlignment(QtCore.Qt.AlignCenter)
        self.deviceLabel_1.setObjectName(_fromUtf8("deviceLabel_1"))
        self.horizontalLayout_2.addWidget(self.deviceLabel_1)
        self.deviceLabel_2 = QtGui.QLabel(self.getInfoTab)
        self.deviceLabel_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.deviceLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.deviceLabel_2.setObjectName(_fromUtf8("deviceLabel_2"))
        self.horizontalLayout_2.addWidget(self.deviceLabel_2)
        self.deviceLabel_3 = QtGui.QLabel(self.getInfoTab)
        self.deviceLabel_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.deviceLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.deviceLabel_3.setObjectName(_fromUtf8("deviceLabel_3"))
        self.horizontalLayout_2.addWidget(self.deviceLabel_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line_13 = QtGui.QFrame(self.getInfoTab)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.verticalLayout_2.addWidget(self.line_13)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.infoLabel_0 = QtGui.QLabel(self.getInfoTab)
        self.infoLabel_0.setText(_fromUtf8(""))
        self.infoLabel_0.setScaledContents(True)
        self.infoLabel_0.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.infoLabel_0.setWordWrap(True)
        self.infoLabel_0.setObjectName(_fromUtf8("infoLabel_0"))
        self.horizontalLayout.addWidget(self.infoLabel_0)
        self.line_6 = QtGui.QFrame(self.getInfoTab)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.horizontalLayout.addWidget(self.line_6)
        self.infoLabel_1 = QtGui.QLabel(self.getInfoTab)
        self.infoLabel_1.setText(_fromUtf8(""))
        self.infoLabel_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.infoLabel_1.setObjectName(_fromUtf8("infoLabel_1"))
        self.horizontalLayout.addWidget(self.infoLabel_1)
        self.line_8 = QtGui.QFrame(self.getInfoTab)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.horizontalLayout.addWidget(self.line_8)
        self.infoLabel_2 = QtGui.QLabel(self.getInfoTab)
        self.infoLabel_2.setText(_fromUtf8(""))
        self.infoLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.infoLabel_2.setObjectName(_fromUtf8("infoLabel_2"))
        self.horizontalLayout.addWidget(self.infoLabel_2)
        self.line_10 = QtGui.QFrame(self.getInfoTab)
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.horizontalLayout.addWidget(self.line_10)
        self.infoLabel_3 = QtGui.QLabel(self.getInfoTab)
        self.infoLabel_3.setText(_fromUtf8(""))
        self.infoLabel_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.infoLabel_3.setObjectName(_fromUtf8("infoLabel_3"))
        self.horizontalLayout.addWidget(self.infoLabel_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.getInfoTab, _fromUtf8(""))
        self.setInfoTab = QtGui.QWidget()
        self.setInfoTab.setObjectName(_fromUtf8("setInfoTab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.setInfoTab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.deviceInfoLabel = QtGui.QLabel(self.setInfoTab)
        self.deviceInfoLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.deviceInfoLabel.setObjectName(_fromUtf8("deviceInfoLabel"))
        self.verticalLayout_5.addWidget(self.deviceInfoLabel)
        self.infoDeviceComboBox = QtGui.QComboBox(self.setInfoTab)
        self.infoDeviceComboBox.setObjectName(_fromUtf8("infoDeviceComboBox"))
        self.verticalLayout_5.addWidget(self.infoDeviceComboBox)
        self.line = QtGui.QFrame(self.setInfoTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line.setFont(font)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_5.addWidget(self.line)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.setSerialNumberPushButton = QtGui.QPushButton(self.setInfoTab)
        self.setSerialNumberPushButton.setObjectName(_fromUtf8("setSerialNumberPushButton"))
        self.gridLayout_6.addWidget(self.setSerialNumberPushButton, 0, 0, 1, 1)
        self.getSerialNumberPushButton = QtGui.QPushButton(self.setInfoTab)
        self.getSerialNumberPushButton.setObjectName(_fromUtf8("getSerialNumberPushButton"))
        self.gridLayout_6.addWidget(self.getSerialNumberPushButton, 1, 0, 1, 1)
        self.serialNumberSpinBox = QtGui.QSpinBox(self.setInfoTab)
        self.serialNumberSpinBox.setMaximum(255)
        self.serialNumberSpinBox.setObjectName(_fromUtf8("serialNumberSpinBox"))
        self.gridLayout_6.addWidget(self.serialNumberSpinBox, 0, 1, 1, 1)
        self.serialNumberLabel = QtGui.QLabel(self.setInfoTab)
        self.serialNumberLabel.setText(_fromUtf8(""))
        self.serialNumberLabel.setObjectName(_fromUtf8("serialNumberLabel"))
        self.gridLayout_6.addWidget(self.serialNumberLabel, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_6)
        self.line_2 = QtGui.QFrame(self.setInfoTab)
        self.line_2.setMinimumSize(QtCore.QSize(0, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_5.addWidget(self.line_2)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.nameLineEdit = QtGui.QLineEdit(self.setInfoTab)
        self.nameLineEdit.setObjectName(_fromUtf8("nameLineEdit"))
        self.gridLayout_7.addWidget(self.nameLineEdit, 0, 1, 1, 1)
        self.setNamePushButton = QtGui.QPushButton(self.setInfoTab)
        self.setNamePushButton.setObjectName(_fromUtf8("setNamePushButton"))
        self.gridLayout_7.addWidget(self.setNamePushButton, 0, 0, 1, 1)
        self.getNamePushButton = QtGui.QPushButton(self.setInfoTab)
        self.getNamePushButton.setObjectName(_fromUtf8("getNamePushButton"))
        self.gridLayout_7.addWidget(self.getNamePushButton, 1, 0, 1, 1)
        self.nameLabel = QtGui.QLabel(self.setInfoTab)
        self.nameLabel.setText(_fromUtf8(""))
        self.nameLabel.setObjectName(_fromUtf8("nameLabel"))
        self.gridLayout_7.addWidget(self.nameLabel, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_7)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.tabWidget.addTab(self.setInfoTab, _fromUtf8(""))
        self.valveControlTab = QtGui.QWidget()
        self.valveControlTab.setObjectName(_fromUtf8("valveControlTab"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.valveControlTab)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.valveDeviceComboBox = QtGui.QComboBox(self.valveControlTab)
        self.valveDeviceComboBox.setEditable(False)
        self.valveDeviceComboBox.setObjectName(_fromUtf8("valveDeviceComboBox"))
        self.gridLayout.addWidget(self.valveDeviceComboBox, 1, 0, 1, 1)
        self.valveDeviceLabel = QtGui.QLabel(self.valveControlTab)
        self.valveDeviceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.valveDeviceLabel.setObjectName(_fromUtf8("valveDeviceLabel"))
        self.gridLayout.addWidget(self.valveDeviceLabel, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_8.addLayout(self.verticalLayout)
        self.line_3 = QtGui.QFrame(self.valveControlTab)
        self.line_3.setMinimumSize(QtCore.QSize(0, 40))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_8.addWidget(self.line_3)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.getValveOnPushButton = QtGui.QPushButton(self.valveControlTab)
        self.getValveOnPushButton.setObjectName(_fromUtf8("getValveOnPushButton"))
        self.gridLayout_3.addWidget(self.getValveOnPushButton, 5, 0, 1, 1)
        self.valveOnLabel = QtGui.QLabel(self.valveControlTab)
        self.valveOnLabel.setText(_fromUtf8(""))
        self.valveOnLabel.setObjectName(_fromUtf8("valveOnLabel"))
        self.gridLayout_3.addWidget(self.valveOnLabel, 5, 1, 1, 1)
        self.valveComboBox = QtGui.QComboBox(self.valveControlTab)
        self.valveComboBox.setObjectName(_fromUtf8("valveComboBox"))
        self.gridLayout_3.addWidget(self.valveComboBox, 4, 1, 1, 1)
        self.setValveOnPushButton = QtGui.QPushButton(self.valveControlTab)
        self.setValveOnPushButton.setObjectName(_fromUtf8("setValveOnPushButton"))
        self.gridLayout_3.addWidget(self.setValveOnPushButton, 4, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_3)
        self.setValvesOffPushButton = QtGui.QPushButton(self.valveControlTab)
        self.setValvesOffPushButton.setObjectName(_fromUtf8("setValvesOffPushButton"))
        self.verticalLayout_8.addWidget(self.setValvesOffPushButton)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.tabWidget.addTab(self.valveControlTab, _fromUtf8(""))
        self.mfcControlTab = QtGui.QWidget()
        self.mfcControlTab.setObjectName(_fromUtf8("mfcControlTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.mfcControlTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.mfcDeviceLabel = QtGui.QLabel(self.mfcControlTab)
        self.mfcDeviceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mfcDeviceLabel.setObjectName(_fromUtf8("mfcDeviceLabel"))
        self.gridLayout_2.addWidget(self.mfcDeviceLabel, 0, 0, 1, 1)
        self.mfcLabel = QtGui.QLabel(self.mfcControlTab)
        self.mfcLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mfcLabel.setObjectName(_fromUtf8("mfcLabel"))
        self.gridLayout_2.addWidget(self.mfcLabel, 0, 1, 1, 1)
        self.mfcDeviceComboBox = QtGui.QComboBox(self.mfcControlTab)
        self.mfcDeviceComboBox.setObjectName(_fromUtf8("mfcDeviceComboBox"))
        self.gridLayout_2.addWidget(self.mfcDeviceComboBox, 1, 0, 1, 1)
        self.mfcComboBox = QtGui.QComboBox(self.mfcControlTab)
        self.mfcComboBox.setObjectName(_fromUtf8("mfcComboBox"))
        self.gridLayout_2.addWidget(self.mfcComboBox, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.line_4 = QtGui.QFrame(self.mfcControlTab)
        self.line_4.setMinimumSize(QtCore.QSize(0, 40))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_3.addWidget(self.line_4)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.mfcSettingLabel = QtGui.QLabel(self.mfcControlTab)
        self.mfcSettingLabel.setText(_fromUtf8(""))
        self.mfcSettingLabel.setObjectName(_fromUtf8("mfcSettingLabel"))
        self.gridLayout_5.addWidget(self.mfcSettingLabel, 1, 1, 1, 1)
        self.getMfcSettingPushButton = QtGui.QPushButton(self.mfcControlTab)
        self.getMfcSettingPushButton.setObjectName(_fromUtf8("getMfcSettingPushButton"))
        self.gridLayout_5.addWidget(self.getMfcSettingPushButton, 1, 0, 1, 1)
        self.setMfcPushButton = QtGui.QPushButton(self.mfcControlTab)
        self.setMfcPushButton.setObjectName(_fromUtf8("setMfcPushButton"))
        self.gridLayout_5.addWidget(self.setMfcPushButton, 0, 0, 1, 1)
        self.mfcSettingSpinBox = QtGui.QSpinBox(self.mfcControlTab)
        self.mfcSettingSpinBox.setMaximum(100)
        self.mfcSettingSpinBox.setProperty("value", 100)
        self.mfcSettingSpinBox.setObjectName(_fromUtf8("mfcSettingSpinBox"))
        self.gridLayout_5.addWidget(self.mfcSettingSpinBox, 0, 1, 1, 1)
        self.getMfcMeasurePushButton = QtGui.QPushButton(self.mfcControlTab)
        self.getMfcMeasurePushButton.setObjectName(_fromUtf8("getMfcMeasurePushButton"))
        self.gridLayout_5.addWidget(self.getMfcMeasurePushButton, 2, 0, 1, 1)
        self.mfcMeasureLabel = QtGui.QLabel(self.mfcControlTab)
        self.mfcMeasureLabel.setText(_fromUtf8(""))
        self.mfcMeasureLabel.setObjectName(_fromUtf8("mfcMeasureLabel"))
        self.gridLayout_5.addWidget(self.mfcMeasureLabel, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_5)
        self.mfcErrorLabel = QtGui.QLabel(self.mfcControlTab)
        self.mfcErrorLabel.setText(_fromUtf8(""))
        self.mfcErrorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mfcErrorLabel.setObjectName(_fromUtf8("mfcErrorLabel"))
        self.verticalLayout_3.addWidget(self.mfcErrorLabel)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.tabWidget.addTab(self.mfcControlTab, _fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLicense = QtGui.QAction(MainWindow)
        self.actionLicense.setObjectName(_fromUtf8("actionLicense"))
        self.actionE_xit = QtGui.QAction(MainWindow)
        self.actionE_xit.setObjectName(_fromUtf8("actionE_xit"))
        self.actionUsage = QtGui.QAction(MainWindow)
        self.actionUsage.setObjectName(_fromUtf8("actionUsage"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Arduino Olfactometer GUI v0.1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.getInfoPushButton.setText(QtGui.QApplication.translate("MainWindow", "Get Info", None, QtGui.QApplication.UnicodeUTF8))
        self.deviceCountLabel.setText(QtGui.QApplication.translate("MainWindow", "Olfactometer Count:", None, QtGui.QApplication.UnicodeUTF8))
        self.deviceLabel_0.setText(QtGui.QApplication.translate("MainWindow", "Olfactometer 0", None, QtGui.QApplication.UnicodeUTF8))
        self.deviceLabel_1.setText(QtGui.QApplication.translate("MainWindow", "Olfactometer 1", None, QtGui.QApplication.UnicodeUTF8))
        self.deviceLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Olfactometer 2", None, QtGui.QApplication.UnicodeUTF8))
        self.deviceLabel_3.setText(QtGui.QApplication.translate("MainWindow", "Olfactometer 3", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.getInfoTab), QtGui.QApplication.translate("MainWindow", "Get Olfactometer Info", None, QtGui.QApplication.UnicodeUTF8))
        self.deviceInfoLabel.setText(QtGui.QApplication.translate("MainWindow", "Olfactometer", None, QtGui.QApplication.UnicodeUTF8))
        self.setSerialNumberPushButton.setText(QtGui.QApplication.translate("MainWindow", "Set Olfactometer Serial Number", None, QtGui.QApplication.UnicodeUTF8))
        self.getSerialNumberPushButton.setText(QtGui.QApplication.translate("MainWindow", "Get Olfactometer Serial Number", None, QtGui.QApplication.UnicodeUTF8))
        self.setNamePushButton.setText(QtGui.QApplication.translate("MainWindow", "Set Olfactometer Name", None, QtGui.QApplication.UnicodeUTF8))
        self.getNamePushButton.setText(QtGui.QApplication.translate("MainWindow", "Get Olfactometer Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.setInfoTab), QtGui.QApplication.translate("MainWindow", "Set Olfactometer Info", None, QtGui.QApplication.UnicodeUTF8))
        self.valveDeviceLabel.setText(QtGui.QApplication.translate("MainWindow", "Olfactometer", None, QtGui.QApplication.UnicodeUTF8))
        self.getValveOnPushButton.setText(QtGui.QApplication.translate("MainWindow", "Get Valve Set to \'On\'", None, QtGui.QApplication.UnicodeUTF8))
        self.setValveOnPushButton.setText(QtGui.QApplication.translate("MainWindow", "Set Valve On", None, QtGui.QApplication.UnicodeUTF8))
        self.setValvesOffPushButton.setText(QtGui.QApplication.translate("MainWindow", "Set All Valves Off", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.valveControlTab), QtGui.QApplication.translate("MainWindow", "Valve Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.mfcDeviceLabel.setText(QtGui.QApplication.translate("MainWindow", "Olfactometer", None, QtGui.QApplication.UnicodeUTF8))
        self.mfcLabel.setText(QtGui.QApplication.translate("MainWindow", "MFC", None, QtGui.QApplication.UnicodeUTF8))
        self.getMfcSettingPushButton.setText(QtGui.QApplication.translate("MainWindow", "Get MFC Percent Capacity Setting", None, QtGui.QApplication.UnicodeUTF8))
        self.setMfcPushButton.setText(QtGui.QApplication.translate("MainWindow", "Set MFC Percent Capacity", None, QtGui.QApplication.UnicodeUTF8))
        self.getMfcMeasurePushButton.setText(QtGui.QApplication.translate("MainWindow", "Get MFC Percent Capacity Measure", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mfcControlTab), QtGui.QApplication.translate("MainWindow", "MFC Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLicense.setText(QtGui.QApplication.translate("MainWindow", "License", None, QtGui.QApplication.UnicodeUTF8))
        self.actionE_xit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUsage.setText(QtGui.QApplication.translate("MainWindow", "Usage", None, QtGui.QApplication.UnicodeUTF8))

